--
-- PostgreSQL database dump
--

-- \restrict Uw5CNA7bXR0Fe5U1d4g4kGHOZFoHGaTPjOnuzUdtXawkTbTb3ryYsATEHeqA7ju

-- Dumped from database version 15.14 (Debian 15.14-1.pgdg13+1)
-- Dumped by pg_dump version 15.14 (Debian 15.14-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: app_user; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.app_user (
    created_at timestamp(6) without time zone NOT NULL,
    role_id bigint NOT NULL,
    user_id bigint NOT NULL,
    email character varying(255) NOT NULL,
    password_hash character varying(255) NOT NULL,
    username character varying(255) NOT NULL
);


--
-- Name: app_user_user_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.app_user ALTER COLUMN user_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.app_user_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: position; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."position" (
    position_id bigint NOT NULL,
    position_name character varying(255)
);


--
-- Name: position_position_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."position" ALTER COLUMN position_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.position_position_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: project; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.project (
    end_date date,
    start_date date,
    created_at timestamp(6) without time zone,
    created_by bigint,
    project_id bigint NOT NULL,
    updated_at timestamp(6) without time zone,
    description character varying(255),
    name character varying(255) NOT NULL,
    url character varying(255)
);


--
-- Name: project_leader; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.project_leader (
    leader_id bigint NOT NULL,
    project_id bigint NOT NULL,
    worker_id bigint NOT NULL
);


--
-- Name: project_leader_leader_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.project_leader ALTER COLUMN leader_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.project_leader_leader_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: project_member; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.project_member (
    member_id bigint NOT NULL,
    project_id bigint NOT NULL,
    worker_id bigint NOT NULL
);


--
-- Name: project_member_member_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.project_member ALTER COLUMN member_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.project_member_member_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: project_project_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.project ALTER COLUMN project_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.project_project_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: role; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.role (
    role_id bigint NOT NULL,
    role_name character varying(255)
);


--
-- Name: role_role_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.role ALTER COLUMN role_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.role_role_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: task; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.task (
    deadline timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    assigned_to_id bigint,
    created_at timestamp(6) without time zone,
    created_by_id bigint,
    project_id bigint,
    task_id bigint NOT NULL,
    task_number bigint,
    task_priority_id bigint,
    task_status_id bigint,
    task_type_id bigint,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    technology character varying(100),
    description text,
    title character varying(255) NOT NULL
);


--
-- Name: task_activity; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.task_activity (
    author_id bigint,
    created_at timestamp(6) without time zone,
    project_id bigint,
    task_activity_id bigint NOT NULL,
    task_id bigint,
    updated_at timestamp(6) without time zone,
    note character varying(255) NOT NULL
);


--
-- Name: task_activity_changes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.task_activity_changes (
    task_activity_changes_id bigint NOT NULL,
    task_activity_id bigint,
    field character varying(255) NOT NULL,
    new_value character varying(255),
    old_value character varying(255)
);


--
-- Name: task_activity_changes_task_activity_changes_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.task_activity_changes ALTER COLUMN task_activity_changes_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.task_activity_changes_task_activity_changes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: task_activity_task_activity_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.task_activity ALTER COLUMN task_activity_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.task_activity_task_activity_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: task_priority; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.task_priority (
    task_priority_id bigint NOT NULL,
    name character varying(50) NOT NULL
);


--
-- Name: task_priority_task_priority_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.task_priority ALTER COLUMN task_priority_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.task_priority_task_priority_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: task_status; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.task_status (
    task_status_id bigint NOT NULL,
    name character varying(50) NOT NULL
);


--
-- Name: task_status_task_status_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.task_status ALTER COLUMN task_status_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.task_status_task_status_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: task_task_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.task ALTER COLUMN task_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.task_task_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: task_type; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.task_type (
    task_type_id bigint NOT NULL,
    name character varying(50) NOT NULL
);


--
-- Name: task_type_task_type_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.task_type ALTER COLUMN task_type_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.task_type_task_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: worker; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.worker (
    hire_date timestamp(6) without time zone,
    position_id bigint,
    user_id bigint,
    worker_id bigint NOT NULL,
    first_name character varying(255),
    last_name character varying(255),
    phone_number character varying(255)
);


--
-- Name: worker_worker_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.worker ALTER COLUMN worker_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.worker_worker_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: app_user app_user_email_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_user
    ADD CONSTRAINT app_user_email_key UNIQUE (email);


--
-- Name: app_user app_user_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_user
    ADD CONSTRAINT app_user_pkey PRIMARY KEY (user_id);


--
-- Name: app_user app_user_username_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_user
    ADD CONSTRAINT app_user_username_key UNIQUE (username);


--
-- Name: position position_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."position"
    ADD CONSTRAINT position_pkey PRIMARY KEY (position_id);


--
-- Name: project_leader project_leader_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.project_leader
    ADD CONSTRAINT project_leader_pkey PRIMARY KEY (leader_id);


--
-- Name: project_leader project_leader_project_id_worker_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.project_leader
    ADD CONSTRAINT project_leader_project_id_worker_id_key UNIQUE (project_id, worker_id);


--
-- Name: project_member project_member_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.project_member
    ADD CONSTRAINT project_member_pkey PRIMARY KEY (member_id);


--
-- Name: project project_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.project
    ADD CONSTRAINT project_pkey PRIMARY KEY (project_id);


--
-- Name: role role_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.role
    ADD CONSTRAINT role_pkey PRIMARY KEY (role_id);


--
-- Name: task_activity_changes task_activity_changes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.task_activity_changes
    ADD CONSTRAINT task_activity_changes_pkey PRIMARY KEY (task_activity_changes_id);


--
-- Name: task_activity task_activity_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.task_activity
    ADD CONSTRAINT task_activity_pkey PRIMARY KEY (task_activity_id);


--
-- Name: task task_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.task
    ADD CONSTRAINT task_pkey PRIMARY KEY (task_id);


--
-- Name: task_priority task_priority_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.task_priority
    ADD CONSTRAINT task_priority_pkey PRIMARY KEY (task_priority_id);


--
-- Name: task_status task_status_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.task_status
    ADD CONSTRAINT task_status_pkey PRIMARY KEY (task_status_id);


--
-- Name: task_type task_type_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.task_type
    ADD CONSTRAINT task_type_pkey PRIMARY KEY (task_type_id);


--
-- Name: worker worker_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.worker
    ADD CONSTRAINT worker_pkey PRIMARY KEY (worker_id);


--
-- Name: worker worker_user_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.worker
    ADD CONSTRAINT worker_user_id_key UNIQUE (user_id);


--
-- Name: project_member fk103dwxad12nbaxtmnwus4eft2; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.project_member
    ADD CONSTRAINT fk103dwxad12nbaxtmnwus4eft2 FOREIGN KEY (project_id) REFERENCES public.project(project_id);


--
-- Name: task fk39t114vuu54mh3wqt50wc2vq4; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.task
    ADD CONSTRAINT fk39t114vuu54mh3wqt50wc2vq4 FOREIGN KEY (task_status_id) REFERENCES public.task_status(task_status_id);


--
-- Name: task fk3s63t73vthpjk6vpwr3s3wtlg; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.task
    ADD CONSTRAINT fk3s63t73vthpjk6vpwr3s3wtlg FOREIGN KEY (task_priority_id) REFERENCES public.task_priority(task_priority_id);


--
-- Name: project_leader fk48g2bhs682b7ti2p2rmkn0nae; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.project_leader
    ADD CONSTRAINT fk48g2bhs682b7ti2p2rmkn0nae FOREIGN KEY (project_id) REFERENCES public.project(project_id);


--
-- Name: app_user fk49hx9nj6onfot1fxtonj986ab; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_user
    ADD CONSTRAINT fk49hx9nj6onfot1fxtonj986ab FOREIGN KEY (role_id) REFERENCES public.role(role_id);


--
-- Name: worker fk60piyfi2ou4mq8oikc6gquhr9; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.worker
    ADD CONSTRAINT fk60piyfi2ou4mq8oikc6gquhr9 FOREIGN KEY (user_id) REFERENCES public.app_user(user_id);


--
-- Name: project_member fk6wswmesfnpevojoogg0jh9j5l; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.project_member
    ADD CONSTRAINT fk6wswmesfnpevojoogg0jh9j5l FOREIGN KEY (worker_id) REFERENCES public.worker(worker_id);


--
-- Name: task fk7pubtrvmiv3ul001yhj7lq89k; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.task
    ADD CONSTRAINT fk7pubtrvmiv3ul001yhj7lq89k FOREIGN KEY (task_type_id) REFERENCES public.task_type(task_type_id);


--
-- Name: task_activity fk9khokjsoqb086s5soky7k5vdu; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.task_activity
    ADD CONSTRAINT fk9khokjsoqb086s5soky7k5vdu FOREIGN KEY (project_id) REFERENCES public.project(project_id);


--
-- Name: task fkdqccriy5wkjfxx5e84apwwb7m; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.task
    ADD CONSTRAINT fkdqccriy5wkjfxx5e84apwwb7m FOREIGN KEY (created_by_id) REFERENCES public.worker(worker_id);


--
-- Name: task fkk8qrwowg31kx7hp93sru1pdqa; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.task
    ADD CONSTRAINT fkk8qrwowg31kx7hp93sru1pdqa FOREIGN KEY (project_id) REFERENCES public.project(project_id);


--
-- Name: task_activity_changes fkkeqdyplxp5lnno24ipvwwuysi; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.task_activity_changes
    ADD CONSTRAINT fkkeqdyplxp5lnno24ipvwwuysi FOREIGN KEY (task_activity_id) REFERENCES public.task_activity(task_activity_id);


--
-- Name: task fklahhx8ki54573dme4l7cysew0; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.task
    ADD CONSTRAINT fklahhx8ki54573dme4l7cysew0 FOREIGN KEY (assigned_to_id) REFERENCES public.worker(worker_id);


--
-- Name: task_activity fklaroqr2nm83mmm60w6fq0rxu3; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.task_activity
    ADD CONSTRAINT fklaroqr2nm83mmm60w6fq0rxu3 FOREIGN KEY (author_id) REFERENCES public.worker(worker_id);


--
-- Name: task_activity fkltxg022u61n4gbne790ukc9i1; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.task_activity
    ADD CONSTRAINT fkltxg022u61n4gbne790ukc9i1 FOREIGN KEY (task_id) REFERENCES public.task(task_id);


--
-- Name: project_leader fkm4q0cyh5ceelm3laobnhfy6oc; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.project_leader
    ADD CONSTRAINT fkm4q0cyh5ceelm3laobnhfy6oc FOREIGN KEY (worker_id) REFERENCES public.worker(worker_id);


--
-- Name: worker fkmvbwx0b3vqbnrkp6jeslxotjp; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.worker
    ADD CONSTRAINT fkmvbwx0b3vqbnrkp6jeslxotjp FOREIGN KEY (position_id) REFERENCES public."position"(position_id);


--
-- Name: project fkpxkh8spyaqeon21642nmt70k8; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.project
    ADD CONSTRAINT fkpxkh8spyaqeon21642nmt70k8 FOREIGN KEY (created_by) REFERENCES public.worker(worker_id);


--
-- PostgreSQL database dump complete
--

-- \unrestrict Uw5CNA7bXR0Fe5U1d4g4kGHOZFoHGaTPjOnuzUdtXawkTbTb3ryYsATEHeqA7ju
