CREATE TABLE public.workspace (
  workspace_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name         VARCHAR(255) NOT NULL,
  created_at   TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now()
);

INSERT INTO public.workspace(name) VALUES ('PUBLIC_DEMO');

ALTER TABLE public.worker
  ADD CONSTRAINT uq_worker_user UNIQUE (user_id);

CREATE TABLE public.workspace_member (
  workspace_member_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  workspace_id BIGINT NOT NULL REFERENCES public.workspace(workspace_id) ON DELETE CASCADE,
  worker_id    BIGINT NOT NULL REFERENCES public.worker(worker_id) ON DELETE CASCADE,
  joined_at    TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
  UNIQUE (workspace_id, worker_id)
);

INSERT INTO public.workspace_member (workspace_id, worker_id)
SELECT wsdemo.workspace_id, w.worker_id
FROM public.worker w
CROSS JOIN LATERAL (
  SELECT workspace_id FROM public.workspace WHERE name='PUBLIC_DEMO' LIMIT 1
) AS wsdemo
ON CONFLICT (workspace_id, worker_id) DO NOTHING;

ALTER TABLE public.project
  ADD COLUMN workspace_id BIGINT;

UPDATE public.project p
SET workspace_id = (SELECT workspace_id FROM public.workspace WHERE name='PUBLIC_DEMO' LIMIT 1)
WHERE p.workspace_id IS NULL;

ALTER TABLE public.project
  ALTER COLUMN workspace_id SET NOT NULL;

ALTER TABLE public.project
  ADD CONSTRAINT fk_project_workspace
  FOREIGN KEY (workspace_id) REFERENCES public.workspace(workspace_id) ON DELETE CASCADE;

ALTER TABLE public.project_leader
  ADD COLUMN workspace_id BIGINT,
  ADD COLUMN workspace_member_id BIGINT;

ALTER TABLE public.project_member
  ADD COLUMN workspace_id BIGINT,
  ADD COLUMN workspace_member_id BIGINT;

UPDATE public.project_leader pl
SET workspace_id = p.workspace_id
FROM public.project p
WHERE p.project_id = pl.project_id AND pl.workspace_id IS NULL;

UPDATE public.project_member pm
SET workspace_id = p.workspace_id
FROM public.project p
WHERE p.project_id = pm.project_id AND pm.workspace_id IS NULL;

-- Ensure there is a workspace_member row for each (workspace, worker) pair we reference
INSERT INTO public.workspace_member (workspace_id, worker_id)
SELECT DISTINCT pl.workspace_id, pl.worker_id
FROM public.project_leader pl
ON CONFLICT (workspace_id, worker_id) DO NOTHING;

INSERT INTO public.workspace_member (workspace_id, worker_id)
SELECT DISTINCT pm.workspace_id, pm.worker_id
FROM public.project_member pm
ON CONFLICT (workspace_id, worker_id) DO NOTHING;

UPDATE public.project_leader pl
SET workspace_member_id = wm.workspace_member_id
FROM public.workspace_member wm
WHERE wm.workspace_id = pl.workspace_id
  AND wm.worker_id    = pl.worker_id
  AND pl.workspace_member_id IS NULL;

UPDATE public.project_member pm
SET workspace_member_id = wm.workspace_member_id
FROM public.workspace_member wm
WHERE wm.workspace_id = pm.workspace_id
  AND wm.worker_id    = pm.worker_id
  AND pm.workspace_member_id IS NULL;

ALTER TABLE public.project_leader
  ALTER COLUMN workspace_id SET NOT NULL,
  ALTER COLUMN workspace_member_id SET NOT NULL;

ALTER TABLE public.project_member
  ALTER COLUMN workspace_id SET NOT NULL,
  ALTER COLUMN workspace_member_id SET NOT NULL;

ALTER TABLE public.workspace_member
  ADD CONSTRAINT uq_ws_member_composite UNIQUE (workspace_id, workspace_member_id);

ALTER TABLE public.project
  ADD CONSTRAINT uq_project_ws_composite UNIQUE (workspace_id, project_id);

ALTER TABLE public.project_leader
  ADD CONSTRAINT fk_pl_project_ws
    FOREIGN KEY (workspace_id, project_id)
    REFERENCES public.project (workspace_id, project_id) ON DELETE CASCADE,
  ADD CONSTRAINT fk_pl_ws_member
    FOREIGN KEY (workspace_id, workspace_member_id)
    REFERENCES public.workspace_member (workspace_id, workspace_member_id) ON DELETE CASCADE;

ALTER TABLE public.project_member
  ADD CONSTRAINT fk_pm_project_ws
    FOREIGN KEY (workspace_id, project_id)
    REFERENCES public.project (workspace_id, project_id) ON DELETE CASCADE,
  ADD CONSTRAINT fk_pm_ws_member
    FOREIGN KEY (workspace_id, workspace_member_id)
    REFERENCES public.workspace_member (workspace_id, workspace_member_id) ON DELETE CASCADE;

CREATE TABLE public.user_discoverability (
  id   BIGINT PRIMARY KEY,
  code VARCHAR(20) UNIQUE NOT NULL
);
INSERT INTO public.user_discoverability(id, code) VALUES
  (1,'NONE'), (2,'WORKSPACE'), (3,'PUBLIC_DEMO');

ALTER TABLE public.app_user
  ADD COLUMN discoverability_id BIGINT NOT NULL DEFAULT 1
    REFERENCES public.user_discoverability(id);

CREATE INDEX idx_ws_member_ws_worker ON public.workspace_member (workspace_id, worker_id);
CREATE INDEX idx_pl_project          ON public.project_leader (workspace_id, project_id);
CREATE INDEX idx_pm_project          ON public.project_member (workspace_id, project_id);
